server.port=8083

spring.application.name=booking-service
spring.datasource.url=jdbc:postgresql://localhost:5433/Booking-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

grpc.server.port=9093
grpc.client.trip-service.address=discovery:///TRIP-SERVICE
grpc.client.trip-service.negotiation-type=plaintext
grpc.client.notification-service.address=discovery:///NOTIFICATION-SERVICE
grpc.client.notification-service.negotiation-type=plaintext

app.jwt.secret=myVerySecretKeyForJWTSigningThatIsLongEnough123456
